
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Конфигурация Emacs.
** TODO


- [ ] orgmode настройки экспорта
- [ ] разбить конфигурацию не несколько файлов

 Потонцеальные пакеты:

- [ ] flycheck
- [ ] undo-tree
- [ ] Mu4e
- [ ] indium?
- [ ] tern?
- [ ] restclient?
- [ ] org-super-agenda
- [ ] org-noter?
- [ ] org-download?
- [ ] org-cliplink?
- [ ] markdown-mode+?
- [ ] markdown-toc?
- [ ] swiper
- [ ] counsel
- [ ] org-brain
- [ ] json-mode

Данная конфигурация Emacs создана с целью адаптировать его для WEB разработки в самом минималистичном дизайне. 
Целью создания была адаптация под маленькие экраны ноутбуков. Отключены все визуальные элементы emacs.

* Используемые паCкеты
В данном разделе дано описание используемых пакетов.

*** Шрифт Hack
Hack - шрифт моноширинный c однозначным начертанием символов. Необходимо скачать и установить в систему.

Ссылка на проект:

https://github.com/source-foundry/Hack

*** doom-themes

Контрастная тема с черным фоном а также модлайн.

Ссылка на проект:

https://github.com/hlissner/emacs-doom-themes
https://github.com/seagle0128/doom-modeline

*** multiple-cursors

Пакет позволяющий включить несколько курсоров для одновременного ввода в нескольких местах.

Ссылка на проект:

https://github.com/magnars/multiple-cursors.el

*** yasnippet

Пакет для работы со снипетами (заготовками кода).

Ссылка на проект:

http://joaotavora.github.io/yasnippet/snippet-organization.html

*** company

Автодополнение при написании кода.

Ссылка на проект:

http://company-mode.github.io

*** magit

Оболочка для управления git в emacs.

Ссылка на проект:

https://magit.vc

*** indent-guide

Отображает уровень вложенности строк относительно текущей табуляции строки.

Ссылка на проект:

https://github.com/zk-phi/indent-guide

*** markdown-mode

Языковой пакет для markdown.

Ссылка на проект:

https://github.com/jrblevin/markdown-mode

*** web-mode

Мульти языковой пакет.

Ссылка на проект:

http://web-mode.org
*** zoom

Автоматически увеличивает размер активного буфера.

Ссылка на проект:

https://github.com/cyrus-and/zoom

*** auctex

Мульти языковой пакет для Tex подобной разметки (LaTex, XeLatex и т.д).

Ссылка на проект:

https://github.com/jwiegley/auctex

*** htmlize

Оформляет код в HTML для отображения на странице в виде блока.

Ссылка на проект:

https://github.com/hniksic/emacs-htmlize

*** projectile

Управление проектами.

Ссылка на проект:

https://github.com/bbatsov/projectile

*** emmet-mode

Добовляем функционал emmet.

Ссылка на проект:

https://github.com/smihica/emmet-mode

*** pug-mode

Режим pug

Ссылка на проект:

https://github.com/hlissner/emacs-pug-mode

*** js2-mode

js2-mode

Ссылка на проект:

https://github.com/mooz/js2-mode

*** smartparens

smartparens

Ссылка на проект:

https://github.com/Fuco1/smartparens
*** swiper counsel

swiper counsel

Ссылка на проект:

https://github.com/abo-abo/swiper
